baseURL = "http://simplifyvmstest.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "SimplifyVMS"
[markup.goldmark.renderer]
unsafe = true
