[en]
contentDir = "content/english"
copyright = "2023 Copyrights reserved"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Bigspring Hugo"
weight = "0.5"
